spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/mydatabase
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5434/mydatabase
    user: postgres
    password: postgres
